name: 'Build-Android-App'
on:
  push:
    branches:
      - 'main'
jobs:
  build-android-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ secrets.ENV_FILE }}" > .env
    - run: echo $FIREBASE_OPTIONS | base64 -d > lib/firebase_options.dart
      env:
        FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
    - run: echo $FIREBASE_APP_ID_FILE | base64 -d > ios/firebase_app_id_file.json
      env:
        FIREBASE_APP_ID_FILE: ${{ secrets.FIREBASE_APP_ID_FILE }}
    - run: echo $GOOGLE_SERVICES | base64 -d > android/app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    #- run: flutter test
    #- run: flutter build apk
    - run: flutter build appbundle