name: 'Build-Android-App'
on:
  push:
    branches:
      - 'main'
jobs:
  build-android-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ secrets.ENV_FILE }}" > .env
    - run: echo $FIREBASE_OPTIONS | base64 -d > lib/firebase_options.dart
      env:
        SECRETS_FILE_CONTENT: ${{ secrets.FIREBASE_OPTIONS }}
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    #- run: flutter test
    #- run: flutter build apk
    - run: flutter build appbundle